source = ~/.config/hypr/colors/matugen.conf

$font = SF Pro Text
$clock_font = PP Neue Machina Ultrabold

general {
    hide_cursor = false
}

# TODO
# uncomment to enable fingerprint authentication
# auth {
#     fingerprint {
#         enabled = true
#         ready_message = Scan fingerprint to unlock
#         present_message = Scanning...
#         retry_delay = 250 # in milliseconds
#     }
# }

animations {
    enabled = true
    bezier = linear, 1, 1, 0, 0
    animation = fadeIn, 1, 5, linear
    animation = fadeOut, 1, 5, linear
    animation = inputFieldDots, 1, 2, linear
}

background {
    monitor =
    path = screenshot
    blur_passes = 3
}

input-field {
    monitor =
    size = 15%, 5%
    outline_thickness = 2
    inner_color = $inverse_on_surface

    outer_color = $primary 45deg
    check_color = $secondary 120deg
    fail_color = $error 40deg

    font_color = $outline
    fade_on_empty = true
    rounding = 100

    font_family = $font
    placeholder_text = Input password...
    fail_text = $PAMFAIL$FPRINTFAIL

    dots_spacing = 0.2
    position = 0, -300
    halign = center
    valign = center
}

# TIME (Hours)
label {
    monitor =
    text = cmd[update:60000] date +"%H" # update every 60 seconds
    font_size = 175
    font_family = $clock_font

    position = 0, -320
    halign = center
    valign = top
    color = $primary
}

# TIME (Minutes)
label {
    monitor =
    text = cmd[update:60000] date +"%M" # update every 60 seconds
    font_size = 190
    font_family = $clock_font

    position = 0, -520
    halign = center
    valign = top
    color = $on_surface
}

# DATE
label {
    monitor =
    text = cmd[update:60000] date +"%a, %B %d" # update every 60 seconds
    font_size = 20
    font_family = SF Pro Text Medium

    position = 120, -150
    halign = left
    valign = top
    color = $on_surface
}