cursor            #d1bcfd
cursor_text_color #37265d

foreground            #e7e0e8
background            #0f0d13
selection_foreground  #332d41
selection_background  #ccc2db
url_color             #ccc2db

#: black 000000 767676
color0  #141218
color8  #36343a
#: red cc0403 f2201f
color1  #1b127a
color9  #4f42e3
#: green 19cb00 23fd00
color2  #ccc2db
color10 #e9def8
#: yellow cecb00 fffd00
color3  #f0b8c6
color11 #ffd9e2
#: blue 0d73cc 1a8fff
color4  #4e3d75
color12 #d1bcfd
#: magenta cb1ed1 fd28ff
color5  #4a4358
color13 #ccc2db
#: cyan 0dcdcd 14ffff
color6  #643b47
color14 #f0b8c6
#: white dddddd ffffff
color7  #cbc4cf
color15 #e7e0e8

mark1_foreground #220f46
mark1_background #eaddff
mark2_foreground #1e192b
mark2_background #e9def8
mark3_foreground #31101c
mark3_background #ffd9e2

active_tab_foreground #37265d
active_tab_background #d1bcfd
inactive_tab_foreground #eaddff
inactive_tab_background #4e3d75

active_border_color #d1bcfd
inactive_border_color #37265d
# bell_border_color #ff5a00
